version: '3.9'

services:
  jupyter:
    build:
      context: .
    volumes:
      - .:/elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - '8888:8888'
    env_file:
      - .env.dev
