version: '3.9'

services:
  jupyter:
    build:
      context: .
    volumes:
      - .:/elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - '8888:8888'

  kibana:
    image: kibana:8.2.2
    ports:
      - '5601:5601'

  elasticsearch:
    image: elasticsearch:8.2.2
    ports:
      - '9200:9200'
    env_file:
      - .env.dev
